
spring:
  rabbitmq:
    addresses: 192.168.98.128
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1


  ##??????

#  spring.rabbitmq.publisher-returns=true
#  spring.rabbitmq.template.mandatory=true
